---
slug: :miktpub_tmp
depends:
  mikutter: 5.0.5
  plugin:
    - mikutter
version: '0.1.0'
author: takemaro
name: miktpub_tmp
description: part of miktpub -- an ActivityPub federation server plugin for mikutter
